api:
    build: ./backend/
    command: bash -c "php composer.phar install && apache2-foreground"
    volumes:
        - ./backend/:/var/www/html/
        - ./shared:/var/www/html/shared/
    ports:
        - 4445:80
    links:
        - rabbitmq
        - mailer

web:
    image: "kyma/docker-nginx"
    volumes:
        - ./web/:/var/www
        - ./shared:/var/www/shared/
    ports:
        - 4446:80
    links:
        - api

rabbitmq:
    image: "rabbitmq:management"
    ports:
        - 5672:5672
        - 15672:15672

mailer:
    image: "mailhog/mailhog"
    ports:
        - 1025:1025
        - 8025:8025
